[source.crates-io]
replace-with = "ustc"

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-args=-L C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/10.3.0 -l:libgcc.a",
    "-C", "target-feature=+crt-static",
]